import type { AgenticCapability, AgenticFlow, AgenticPlatformLinkage } from '@/api/types/agentic'

export const platformLinkages: AgenticPlatformLinkage[] = [
  {
    id: 'platform-api',
    name: 'GWI Platform API',
    description: 'Data plane for analysis, audiences, variables, and exports.',
    endpoints: ['GET /platform/api/v1/analysis', 'GET /platform/api/v1/audiences'],
    auth: 'token',
  },
  {
    id: 'spark-api',
    name: 'Spark API',
    description: 'Natural-language insights and chat responses.',
    endpoints: ['POST /spark/api/v1/chat', 'GET /spark/api/v1/insights'],
    auth: 'token',
  },
  {
    id: 'spark-mcp',
    name: 'Spark MCP',
    description: 'Agent-to-agent interface for tool calls and collaboration.',
    endpoints: ['POST /spark-api/mcp'],
    auth: 'oauth',
  },
]

export const capabilityInventory: AgenticCapability[] = [
  {
    id: 'brief-interpreter',
    name: 'Brief Interpreter',
    type: 'agent',
    category: 'Orchestration',
    description: 'Classifies briefs and extracts objectives, audiences, markets, and outputs.',
    inputs: ['brief_text', 'role_context'],
    outputs: ['structured_brief', 'intent_tags'],
  },
  {
    id: 'workflow-orchestrator',
    name: 'Workflow Orchestrator',
    type: 'agent',
    category: 'Orchestration',
    description: 'Creates workspace and routes work to appropriate agents and tools.',
    inputs: ['structured_brief', 'capability_inventory'],
    outputs: ['workflow_plan', 'workspace_id'],
  },
  {
    id: 'data-harmonizer',
    name: 'Data Harmonizer',
    type: 'agent',
    category: 'Data Harmonization',
    description: 'Merges GWI, first-party, and external data with provenance.',
    inputs: ['gwi_data', 'first_party_data', 'external_data'],
    outputs: ['harmonized_dataset', 'provenance_log'],
  },
  {
    id: 'audience-profiler',
    name: 'Audience Profiler',
    type: 'agent',
    category: 'Audience & Profiling',
    description: 'Builds, validates, and sizes target audiences.',
    inputs: ['harmonized_dataset', 'audience_rules'],
    outputs: ['audience_id', 'persona_summary'],
  },
  {
    id: 'crosstab-analyst',
    name: 'Crosstab Analyst',
    type: 'tool',
    category: 'Analysis & Crosstab',
    description: 'Runs advanced crosstabs, comparisons, and significance checks.',
    inputs: ['audience_id', 'variables', 'metrics'],
    outputs: ['crosstab_table', 'significance_report'],
  },
  {
    id: 'narrative-agent',
    name: 'Narrative Agent',
    type: 'agent',
    category: 'Narrative & Knowledge',
    description: 'Translates data into clear, client-ready insight narratives.',
    inputs: ['analysis_results', 'tone_of_voice'],
    outputs: ['insight_summary', 'story_beats'],
  },
  {
    id: 'visualization-agent',
    name: 'Visualization Agent',
    type: 'agent',
    category: 'Visualization & Packaging',
    description: 'Creates charts, dashboards, and decks for delivery.',
    inputs: ['insight_summary', 'chart_specs'],
    outputs: ['charts', 'dashboard', 'deck'],
  },
  {
    id: 'governance-agent',
    name: 'Governance Agent',
    type: 'agent',
    category: 'Governance & Compliance',
    description: 'Validates insights against source data with citations.',
    inputs: ['insight_summary', 'provenance_log'],
    outputs: ['validation_report', 'citation_bundle'],
  },
  {
    id: 'connector-agent',
    name: 'Connector Agent',
    type: 'agent',
    category: 'Delivery & Connectors',
    description: 'Delivers outputs to client systems, MCP, and BI tools.',
    inputs: ['deck', 'dashboard', 'exports'],
    outputs: ['delivery_receipts'],
  },
  {
    id: 'advisor-agent',
    name: 'Advisor Agent',
    type: 'agent',
    category: 'Proactivity & ROI',
    description: 'Monitors outcomes, trends, and recommends next steps.',
    inputs: ['campaign_results', 'alerts'],
    outputs: ['recommendations', 'learning_updates'],
  },
]

const baseFlows: AgenticFlow[] = [
  {
    id: 'brief-interpretation',
    name: 'Brief Interpretation Flow',
    description: 'Turns unstructured briefs into guided workflows and outputs.',
    triggers: ['incoming_brief', 'agent_spark_prompt'],
    steps: [
      {
        id: 'step-brief',
        name: 'Brief Interpreter',
        capability_id: 'brief-interpreter',
        description: 'Extract objectives, audiences, markets, and outputs.',
        output_artifacts: ['structured_brief'],
      },
      {
        id: 'step-workflow',
        name: 'Workflow Orchestrator',
        capability_id: 'workflow-orchestrator',
        description: 'Create workspace and route to analysis tools.',
        depends_on: ['step-brief'],
        output_artifacts: ['workspace_id'],
      },
      {
        id: 'step-analysis',
        name: 'Analysis & Audience',
        capability_id: 'audience-profiler',
        description: 'Run background analysis and identify lifts.',
        depends_on: ['step-workflow'],
        output_artifacts: ['audience_id', 'persona_summary'],
      },
      {
        id: 'step-narrative',
        name: 'Narrative & Knowledge',
        capability_id: 'narrative-agent',
        description: 'Translate into contextual insight narrative.',
        depends_on: ['step-analysis'],
        output_artifacts: ['insight_summary'],
      },
      {
        id: 'step-advisor',
        name: 'Advisor',
        capability_id: 'advisor-agent',
        description: 'Prompt next steps or follow-up actions.',
        depends_on: ['step-narrative'],
        output_artifacts: ['recommendations'],
      },
    ],
  },
  {
    id: 'campaign-lifecycle',
    name: 'End-to-End Campaign Flow',
    description: 'Automates the full campaign lifecycle from audience to ROI.',
    triggers: ['campaign_brief', 'post_campaign_data'],
    steps: [
      {
        id: 'step-audience',
        name: 'Audience Profiling',
        capability_id: 'audience-profiler',
        description: 'Identify and size target segments.',
        output_artifacts: ['audience_id'],
      },
      {
        id: 'step-crosstab',
        name: 'Analysis (Crosstab)',
        capability_id: 'crosstab-analyst',
        description: 'Analyze opportunities and behaviors.',
        depends_on: ['step-audience'],
        output_artifacts: ['crosstab_table'],
      },
      {
        id: 'step-narrative',
        name: 'Narrative',
        capability_id: 'narrative-agent',
        description: 'Produce actionable recommendations.',
        depends_on: ['step-crosstab'],
        output_artifacts: ['insight_summary'],
      },
      {
        id: 'step-workflow',
        name: 'Workflow',
        capability_id: 'workflow-orchestrator',
        description: 'Automate report generation and templates.',
        depends_on: ['step-narrative'],
        output_artifacts: ['report', 'dashboard'],
      },
      {
        id: 'step-advisor',
        name: 'Advisor',
        capability_id: 'advisor-agent',
        description: 'Track ROI and learning loops.',
        depends_on: ['step-workflow'],
        output_artifacts: ['learning_updates'],
      },
    ],
  },
]

const specialistFlowDefs = [
  { agentId: 'brief-interpreter', name: 'Brief Interpreter Specialist Flow', capabilityId: 'brief-interpreter' },
  { agentId: 'workflow-orchestrator', name: 'Workflow Orchestrator Specialist Flow', capabilityId: 'workflow-orchestrator' },
  { agentId: 'data-harmonizer', name: 'Data Harmonizer Specialist Flow', capabilityId: 'data-harmonizer' },
  { agentId: 'audience-profiler', name: 'Audience Profiler Specialist Flow', capabilityId: 'audience-profiler' },
  { agentId: 'crosstab-analyst', name: 'Crosstab Analyst Specialist Flow', capabilityId: 'crosstab-analyst' },
  { agentId: 'narrative-agent', name: 'Narrative Agent Specialist Flow', capabilityId: 'narrative-agent' },
  { agentId: 'visualization-agent', name: 'Visualization Agent Specialist Flow', capabilityId: 'visualization-agent' },
  { agentId: 'governance-agent', name: 'Governance Agent Specialist Flow', capabilityId: 'governance-agent' },
  { agentId: 'connector-agent', name: 'Connector Agent Specialist Flow', capabilityId: 'connector-agent' },
  { agentId: 'advisor-agent', name: 'Advisor Agent Specialist Flow', capabilityId: 'advisor-agent' },
] as const

const specialistFlows: AgenticFlow[] = specialistFlowDefs.map((def) => ({
  id: `flow-${def.agentId}`,
  name: def.name,
  description: `Specialist workflow for ${def.name.replace(' Specialist Flow', '')}.`,
  triggers: [`agent_${def.agentId.replace(/-/g, '_')}`, 'agent_spark_prompt'],
  steps: [
    {
      id: `step-${def.agentId}-intake`,
      name: 'Context Intake',
      capability_id: 'brief-interpreter',
      description: 'Capture objective, constraints, and required outputs.',
      output_artifacts: ['context_packet'],
    },
    {
      id: `step-${def.agentId}-execute`,
      name: 'Specialist Execution',
      capability_id: def.capabilityId,
      description: `Run specialist tasks for ${def.name.replace(' Specialist Flow', '')}.`,
      depends_on: [`step-${def.agentId}-intake`],
      output_artifacts: ['specialist_output'],
    },
    {
      id: `step-${def.agentId}-validate`,
      name: 'Validation Gate',
      capability_id: 'governance-agent',
      description: 'Attach citations, confidence, and policy checks.',
      depends_on: [`step-${def.agentId}-execute`],
      output_artifacts: ['validation_report'],
    },
    {
      id: `step-${def.agentId}-handoff`,
      name: 'Delivery Handoff',
      capability_id: 'connector-agent',
      description: 'Package and route outputs to destination systems.',
      depends_on: [`step-${def.agentId}-validate`],
      output_artifacts: ['handoff_note'],
    },
  ],
}))

export const agenticFlows: AgenticFlow[] = [...baseFlows, ...specialistFlows]
